# xxl-job参数配置
xxl:
  job:
    accessToken:
    admin:
      addresses: http://192.168.150.101:28080/xxl-job-admin
    executor:
      appname: qstock-job-executor
      address:
      ip:
      port: 6666
      logpath: .\logs
      logretentiondays: 30